services:
  db:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres || exit 1"]
      interval: 3s
      timeout: 2s
      retries: 20
    volumes:
      - dbdata:/var/lib/postgresql/data
volumes:
  dbdata: {}