name: CI

on:
  push:
  pull_request:

jobs:
  build-and-migrate:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres -d postgres"
          --health-interval=5s
          --health-timeout=2s
          --health-retries=20

    env:
      NODE_ENV: test
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/hospital_app

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm ci

      - name: Create DB
        run: npx tsx db/create-db.ts

      - name: Run migrations
        run: npx tsx db/migrate.ts

      # Optional: run lints/tests here
      # - run: npm run lint
      # - run: npm test