name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: test
      # Dummy URL to satisfy config parsing, no DB started in CI
      DATABASE_URL: postgres://user:pass@localhost:5432/dummy
      JWT_SECRET: ci-secret
      ACCESS_TTL_SECONDS: 900
      REFRESH_TTL_DAYS: 30
      CI: true

    steps:
      - uses: actions/checkout@v4

      - name: Use Node 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - run: npm ci

      - name: Lint
        run: npm run lint

      # Optional explicit test step (coverage also runs tests)
      - name: Test
        run: npm test -- --runInBand

      - name: Coverage
        run: npm run coverage

      - name: Upload coverage
        if: ${{ !env.ACT }}
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage
